inventory form is now working! ...but whenever I submit the new item I get a Uncaught TypeError: inventory.map is not a function error... it was working before so I have a feeling this should be an easy fix i just need to figure it out